DELETE FROM teachers;
INSERT INTO teachers (id, name, subject, subject_label, phase, mode, schedule, track) VALUES ('reda', 'أ/ رضا الفاروق', 'arabic', 'اللغة العربية', NULL, NULL, NULL, NULL);
INSERT INTO teachers (id, name, subject, subject_label, phase, mode, schedule, track) VALUES ('sayed', 'أ/ السيد عبدالعزيز', 'arabic', 'اللغة العربية', NULL, NULL, 'الأربعاء 5–7 مساءً', NULL);
INSERT INTO teachers (id, name, subject, subject_label, phase, mode, schedule, track) VALUES ('salah', 'أ/ محمد صلاح', 'english', 'اللغة الإنجليزية', NULL, NULL, 'الأحد 1–2:30 ظهرًا', NULL);
INSERT INTO teachers (id, name, subject, subject_label, phase, mode, schedule, track) VALUES ('ahmed-atef', 'أ/ احمد عاطف', 'english', 'اللغة الإنجليزية', NULL, NULL, NULL, NULL);
INSERT INTO teachers (id, name, subject, subject_label, phase, mode, schedule, track) VALUES ('milad-mourad', 'أ/ ميلاد مراد', 'english', 'اللغة الإنجليزية', NULL, NULL, 'الأحد 2–4:30 ظهرًا', NULL);
INSERT INTO teachers (id, name, subject, subject_label, phase, mode, schedule, track) VALUES ('adel-nabil', 'أ/ عادل نبيل', 'english', 'اللغة الإنجليزية', NULL, NULL, NULL, NULL);
INSERT INTO teachers (id, name, subject, subject_label, phase, mode, schedule, track) VALUES ('marwan-el-anani', 'مسيو/ مروان العناني', 'french', 'اللغة الفرنسية', NULL, NULL, NULL, NULL);
INSERT INTO teachers (id, name, subject, subject_label, phase, mode, schedule, track) VALUES ('bardeesy', 'مسيو/ محمد البرديسي', 'french', 'اللغة الفرنسية', NULL, NULL, NULL, NULL);
INSERT INTO teachers (id, name, subject, subject_label, phase, mode, schedule, track) VALUES ('hussein-aboleinen', 'مسيو/ حسين أبو العينين', 'french', 'اللغة الفرنسية', NULL, NULL, 'أونلاين', NULL);
INSERT INTO teachers (id, name, subject, subject_label, phase, mode, schedule, track) VALUES ('abdelmoeez', 'هير/ عبدالمعز اسماعيل', 'german', 'اللغة الألمانية', NULL, NULL, 'أونلاين', NULL);
INSERT INTO teachers (id, name, subject, subject_label, phase, mode, schedule, track) VALUES ('essam', 'هير/ عصام خطاب', 'german', 'اللغة الألمانية', NULL, NULL, NULL, NULL);
INSERT INTO teachers (id, name, subject, subject_label, phase, mode, schedule, track) VALUES ('el-qot', 'سنيور/ محمد القط', 'italian', 'اللغة الإيطالية', NULL, NULL, NULL, NULL);
INSERT INTO teachers (id, name, subject, subject_label, phase, mode, schedule, track) VALUES ('tolba', 'محمد طلبه', 'history', 'التاريخ', NULL, 'سنتر واونلاين', 'الثلاثاء 6–9 مساءً', NULL);
INSERT INTO teachers (id, name, subject, subject_label, phase, mode, schedule, track) VALUES ('abdallah-ismail', 'عبدالله اسماعيل', 'history', 'التاريخ', NULL, 'سنتر', 'الاثنين 7–9 مساءً', NULL);
INSERT INTO teachers (id, name, subject, subject_label, phase, mode, schedule, track) VALUES ('tamer-el-qady', 'تامر القاضي', 'physics', 'Physics', 'bac2', 'اونلاين', 'أونلاين', 'لغات');
INSERT INTO teachers (id, name, subject, subject_label, phase, mode, schedule, track) VALUES ('physics', 'احمد سمير', 'physics', 'Physics', 'bac2', 'اونلاين', 'أونلاين', 'لغات');
INSERT INTO teachers (id, name, subject, subject_label, phase, mode, schedule, track) VALUES ('megali', 'أحمد سمير مجلي', 'physics', 'Physics', 'bac2', 'اونلاين', 'أونلاين', 'لغات');
INSERT INTO teachers (id, name, subject, subject_label, phase, mode, schedule, track) VALUES ('nawar', 'احمد نوار', 'physics', 'Physics', 'bac2', 'اونلاين', 'أونلاين', 'لغات');
INSERT INTO teachers (id, name, subject, subject_label, phase, mode, schedule, track) VALUES ('raeia', 'عمر رعيه', 'physics', 'Physics', 'bac2', 'اونلاين', 'أونلاين', 'لغات');
INSERT INTO teachers (id, name, subject, subject_label, phase, mode, schedule, track) VALUES ('gioushy', 'محمد الجيوشي', 'physics', 'Physics', 'bac2', 'سنتر', 'الجمعة 2–5 مساءً', 'لغات');
INSERT INTO teachers (id, name, subject, subject_label, phase, mode, schedule, track) VALUES ('abdelmaaboud', 'محمد عبدالمعبود', 'physics', 'الفيزياء', 'bac2', 'اونلاين', NULL, 'عربي');
INSERT INTO teachers (id, name, subject, subject_label, phase, mode, schedule, track) VALUES ('ahmed-abdelmonem', 'احمد عبدالمنعم', 'physics', 'الفيزياء', 'bac2', 'سنتر', 'السبت 10–1 صباحًا', 'عربي');
INSERT INTO teachers (id, name, subject, subject_label, phase, mode, schedule, track) VALUES ('shenawy', 'اشرف الشناوي', 'chemistry', 'Chemistry', 'bac2', 'اونلاين', 'أونلاين', 'لغات');
INSERT INTO teachers (id, name, subject, subject_label, phase, mode, schedule, track) VALUES ('nasser', 'ناصر البطل', 'chemistry', 'Chemistry', 'bac2', 'اونلاين', 'أونلاين', 'لغات');
INSERT INTO teachers (id, name, subject, subject_label, phase, mode, schedule, track) VALUES ('tarek', 'طارق عصام', 'chemistry', 'Chemistry', 'bac2', 'سنتر', 'الثلاثاء 2–5 عصرًا', 'لغات');
INSERT INTO teachers (id, name, subject, subject_label, phase, mode, schedule, track) VALUES ('mohamed-abdelgawad', 'محمد عبدالجواد', 'chemistry', 'الكيمياء', 'bac2', 'اونلاين', 'أونلاين', 'عربي');
INSERT INTO teachers (id, name, subject, subject_label, phase, mode, schedule, track) VALUES ('khaled-sabry', 'خالد صبري', 'chemistry', 'الكيمياء', 'bac2', 'سنتر', 'الجمعة 5–7 مساءً', 'عربي');
INSERT INTO teachers (id, name, subject, subject_label, phase, mode, schedule, track) VALUES ('chemistry', 'خالد صقر', 'chemistry', 'الكيمياء', 'bac2', 'اونلاين', 'أونلاين', 'عربي');
INSERT INTO teachers (id, name, subject, subject_label, phase, mode, schedule, track) VALUES ('khattab', 'مصطفى خطاب', 'chemistry', 'Chemistry', 'bac2', 'اونلاين', NULL, 'لغات');
INSERT INTO teachers (id, name, subject, subject_label, phase, mode, schedule, track) VALUES ('deif', 'د/ ضيف', 'biology', 'Biology', 'bac2', 'اونلاين', 'أونلاين', 'لغات');
INSERT INTO teachers (id, name, subject, subject_label, phase, mode, schedule, track) VALUES ('biology', 'علي الروبي', 'biology', 'أحياء', 'bac2', 'سنتر', 'الخميس 9–12 صباحًا', 'عربي');
INSERT INTO teachers (id, name, subject, subject_label, phase, mode, schedule, track) VALUES ('biology-biology', 'د/ جميلة', 'biology', 'أحياء', 'bac2', 'سنتر', 'الأربعاء 4–6:30 مساءً', 'عربي');
INSERT INTO teachers (id, name, subject, subject_label, phase, mode, schedule, track) VALUES ('magd', 'محمد مجد', 'math', 'Math', 'bac2', 'سنتر', 'الاثنين 3–5 مساءً · الأربعاء 3–5 عصرًا', 'لغات');
INSERT INTO teachers (id, name, subject, subject_label, phase, mode, schedule, track) VALUES ('sabry', 'محمد صبري', 'math', 'Math', 'bac2', 'سنتر', 'الأحد 3–5:30 عصرًا · الخميس 3:30–5:30 عصرًا', 'لغات');
INSERT INTO teachers (id, name, subject, subject_label, phase, mode, schedule, track) VALUES ('mazen', 'مازن الحيوان', 'math', 'Math', 'bac2', 'سنتر', NULL, 'لغات');
INSERT INTO teachers (id, name, subject, subject_label, phase, mode, schedule, track) VALUES ('ezzat', 'محمد عزت', 'math', 'Math', 'bac2', 'سنتر', 'السبت 1:30–7 عصرًا', 'لغات');
INSERT INTO teachers (id, name, subject, subject_label, phase, mode, schedule, track) VALUES ('sherbini', 'عمر الشربيني', 'math', 'Math', 'bac2', 'اونلاين', 'أونلاين', 'لغات');
INSERT INTO teachers (id, name, subject, subject_label, phase, mode, schedule, track) VALUES ('maged-hassan', 'ماجد حسن', 'math', 'الرياضيات', 'bac2', 'سنتر', NULL, 'عربي');
INSERT INTO teachers (id, name, subject, subject_label, phase, mode, schedule, track) VALUES ('mohamed-naguib', 'محمد نجيب', 'math', 'الرياضيات', 'bac2', 'سنتر', 'الاثنين 4–6 عصرًا · الخميس 4–6 عصرًا', 'عربي');
INSERT INTO teachers (id, name, subject, subject_label, phase, mode, schedule, track) VALUES ('programming', 'محمود يونس', 'programming', 'البرمجة', 'bac2', 'لغات', NULL, NULL);
INSERT INTO teachers (id, name, subject, subject_label, phase, mode, schedule, track) VALUES ('kamal-el-marakbi', 'كمال المراكبي', 'programming', 'البرمجة', 'bac2', 'لغات وعربي', 'الخميس 5–7 عصرًا', NULL);
INSERT INTO teachers (id, name, subject, subject_label, phase, mode, schedule, track) VALUES ('programming-programming', 'محمود عبدالحميد', 'programming', 'البرمجة', 'bac2', NULL, 'الخميس 5–7 عصرًا', NULL);
INSERT INTO teachers (id, name, subject, subject_label, phase, mode, schedule, track) VALUES ('haitham', 'د/ هيثم عطيه', 'business', 'إدارة أعمال', 'bac2', 'عربي ولغات', 'الجمعة 7–9 مساءً', NULL);
INSERT INTO teachers (id, name, subject, subject_label, phase, mode, schedule, track) VALUES ('ahmed-tolba', 'د/ احمد طلبه', 'accounting', 'المحاسبة', 'bac2', 'عربي ولغات', 'الجمعة 7–9 مساءً', NULL);
INSERT INTO teachers (id, name, subject, subject_label, phase, mode, schedule, track) VALUES ('ahmed-amin', 'د/ أحمد أمين', 'accounting', 'Accounting', 'bac2', NULL, NULL, 'لغات');
INSERT INTO teachers (id, name, subject, subject_label, phase, mode, schedule, track) VALUES ('mohamed-badran', 'د/ محمد بدران', 'accounting', 'محاسبة / Accounting', 'bac2', NULL, NULL, 'عربي');
INSERT INTO teachers (id, name, subject, subject_label, phase, mode, schedule, track) VALUES ('ali-salah', 'علي صلاح', 'psychology', 'علم النفس', 'bac2', NULL, 'الجمعة 6:30–8:30 مساءً', NULL);
INSERT INTO teachers (id, name, subject, subject_label, phase, mode, schedule, track) VALUES ('saber-darwish', 'صابر درويش', 'psychology', 'علم النفس', 'bac2', NULL, NULL, NULL);
INSERT INTO teachers (id, name, subject, subject_label, phase, mode, schedule, track) VALUES ('geology', 'سامح نشأت', 'geology', 'جيولوجيا', 'bac3', NULL, 'الأربعاء 1–4 عصرًا', NULL);
INSERT INTO teachers (id, name, subject, subject_label, phase, mode, schedule, track) VALUES ('geology-geology', 'أشرف حمزة', 'geology', 'جيولوجيا', 'bac3', NULL, NULL, NULL);
INSERT INTO teachers (id, name, subject, subject_label, phase, mode, schedule, track) VALUES ('geography', 'أحمد زهران', 'geography', 'الجغرافيا', 'bac3', NULL, 'الأحد 5–7 مساءً', NULL);
INSERT INTO teachers (id, name, subject, subject_label, phase, mode, schedule, track) VALUES ('geography-geography', 'محمد الحلواني', 'geography', 'الجغرافيا', 'bac3', NULL, 'السبت 4–6 مساءً', NULL);
INSERT INTO teachers (id, name, subject, subject_label, phase, mode, schedule, track) VALUES ('magd-statistics', 'محمد مجد', 'statistics', 'إحصاء', 'bac3', NULL, NULL, NULL);
INSERT INTO teachers (id, name, subject, subject_label, phase, mode, schedule, track) VALUES ('mohamed-naguib-statistics', 'محمد نجيب', 'statistics', 'إحصاء', 'bac3', NULL, NULL, NULL);
INSERT INTO teachers (id, name, subject, subject_label, phase, mode, schedule, track) VALUES ('mazen-statistics', 'مازن الحيوان', 'statistics', 'إحصاء', 'bac3', NULL, NULL, NULL);
INSERT INTO teachers (id, name, subject, subject_label, phase, mode, schedule, track) VALUES ('sherbini-statistics', 'عمر الشربيني', 'statistics', 'إحصاء', 'bac3', NULL, NULL, NULL);
